### ISSUE TITLE
Potential issues with your iptables

### ISSUE THREAD

**Issue by authenticdane** [pivpn/pivpn#182]
After reboot of RaspberryPi server, VPN traffic not routed to internet.

pivpn debug results in the following error

::: We detected some potential issues with your iptables.
::: Would you like us to try to fix this? [y/n]: y
::: Attempt at fix completed.

After running debug, routing issues are resolved until next reboot. Client connects with no issues, access to LAN IP address space not impacted. Debug must be run to restore internet connectivity.

**Comment by 0-kaladin** [comment]
What OS do you use?

**Comment by authenticdane** [comment]
Raspbian Jessie Light

**Comment by poacher2k** [comment]
I also encountered this, and now got everything up and running.

As per [this comment](https://www.raspberrypi.org/forums/viewtopic.php?t=17694&p=176040#p453450), what I had to do was (with sudo):
```
$ /sbin/iptables -P FORWARD ACCEPT
$ /sbin/iptables --table nat -A POSTROUTING -o eth0 -j MASQUERADE
```
This only works until you restart though, so add the commands to `/etc/rc.local` in between `fi` and `exit 0` (without sudo here).

The end of my `/etc/rc.local` now looks like this:
```
fi
/sbin/iptables -P FORWARD ACCEPT
/sbin/iptables --table nat -A POSTROUTING -o eth0 -j MASQUERADE
exit 0
```

Hope this helps!

**Comment by 0-kaladin** [comment]
do you guys have the command "netfilter-persistent save" on your pi's?

**Comment by poacher2k** [comment]
@0-kaladin: I have this command available, and can run it with root. Should I? 

Btw, thank you for the awesome installer! I spent the entire first half of my Sunday attempting to setup a vpn manually on my pi, and after being close to giving up I found pivpn and got up and running in less than two hours, with a setup I have much more confidence in than what I could've done myself.

**Comment by 0-kaladin** [comment]
I'd like to know if you run netfilter-persistent save.  remove or comment out your lines in rc.local.  then reboot.  are your iptables rules still in place?  they should be.

**Comment by CoderCoyote** [comment]
@0-kaladin I am having the same problem since last Friday when I updated my Pi. I missed the impact during the weekend and when I tried today (Monday) from work I was connecting to the VPN but with LAN access only. Similar to @poacher2k when manually added the following rule it started working fine.

`/sbin/iptables --table nat -A POSTROUTING -o eth0 -j MASQUERADE`

After seeing your comment checked whether I do have `netfilter-persistent` installed and running - it is in there alright. Also checked if I have it in `/etc/rc.local`, however, there was no such entry.

After updating (by adding the above rule) the iptables and running `netfilter-persistent` save (which supposedly should save the current state of the iptables) when I reboot the iptables end up empty. Curiously I checked the config file for netfilter-persistent located at `/etc/default/netfilter-persistent` to see if my updated iptables rules were saved and it was there fine. So, I tried to kick start it manually `netfilter-persistent start` and worked fine.

Now, I have added `netfilter-persistent start` on my `/etc/rc.local` and seems to be working all fine. 

But I am curious if this sort of solution was the right one or am I filling up the memory with needless applications?

Thanks

**Comment by mcannon-gso** [comment]
@0-kaladin I had this same issue and this is how I resolved it on Rpi Jessie.
1 - After Install of piVPN I went ahead and ran the pivpn debug. This showed and corrected the issues.
2 - I then ran iptables-save > /etc/iptables.up.rules as root
3 - Created file /etc/network/if-pre-up.d/iptables with a chmod +x
4 - Edited the file to add the following lines...
  #!/bin/sh
  /sbin/iptables-restore < /etc/iptables.up.rules
5 - Then rebooted and viola. iptables were fixed automatically..

Hope this helps someone out.... :-)

**Comment by cfcolaco** [comment]
@0-kaladin @redfast00 

This seems not to be happening anymore, and when it does is never directly associated with pivpn but with some other packages // wrong repos // etc etc .. 

What is your opinion on what to do with this issue?

**Comment by 0-kaladin** [comment]
Not sure. Ip tables issues have been off on since the start. Though I know I'm applying correctly, there could be edge cases the script could better handle. I could also do it the "incorrect" way by applying in rc.local.
As more OS added, some may need to be handled differently.
... And I guess none of that answered your question.

**Comment by cfcolaco** [comment]
ahahah @0-kaladin 

Nope, it hasn't! so I still don't know what to do with this issue! xD

**Comment by tomekit** [comment]
@poacher2k Thank you for your solution. Worked like a charm on my fresh Pi and PiVPN.

**Comment by 3shirts** [comment]
Hi, Just wanted to add that I was having this issue on Raspian Buster and fixed it using both @poacher2k and @CoderCoyote advice. Added those lines to rc.local including netfilter-persistent start and it's working great now. Surviving reboots without having to run debug every time!

Thanks
