### ISSUE TITLE
Support for Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by ZV00** [pivpn/pivpn#653]
Hello,

I wanted to find out if anyone has gotten around to trying out PiVPN on 18.04 LTS with Pi-Hole 4.1? 

I know as of right now it is not **officially** supported, but is this something that will be coming soon, and should I want to install it on an 18.04 LTS machine for now? 

Thanks so much!

**Comment by orazioedoardo** [comment]
Not tested but it should work. Could you report your experience?

**Comment by ZV00** [comment]
I was able to successfully install it, but I have run into an issue with getting it working. Essentially... I haven't figured out what to do in order to get the profile that I created with `pivpn add` to be used. When I attempt to use a given profile on another device, the import into OpenVPN Connect succeeds, but it does not connect.

**Comment by ZV00** [comment]
Does not work on the Ubuntu device and does not work on a Mac mini on my network with the .ovpn profile.

**Comment by orazioedoardo** [comment]
Try from a different network, like a cellular network. Some routers prevent devices within their network to reach other devices in the same network (your server in this case) using the public IP.

If it still doesn’t work, post the server log `cat /var/log/openvpn.log`. Mask IP and client name if you want.

**Comment by jmh62** [comment]
I have been able to get PiVPN running on my Odroid XU4 running Ubuntu Mate, version 18.04 LTS.  The only issue I had was a little difficulty running "pivpn add" after installation.  Not sure exactly what the problem was, but I did get it organized.  When trying to run "pivpn add" I received an error showing that it could not create the ovpns directory.  The 'quick' fix I found was to reinstall, but this time I ran curl as superuser.  This doesn't really make sense to me, but it did work.  I'll let you know if I am able to make any more sense out of this as I do more testing.  

P.S.:  PiVPN is awesome!  Very appreciative of the effort that was obviously put into this project.  Will be donating.

**Comment by orazioedoardo** [comment]
@jmh62 There is some bug where the user field in the script is not populated, resulting in a broken path (e.g. /home//ovpns/client.ovpn). Many people solved the issue by manually downloading and executing the script (instead of piping to bash) or change the position where you use sudo. I fixed one issue that lead to this but apparently it still happens #645

**Comment by vik0** [comment]
Hi! I am having a similar issue. I am able to connect to the server but unable to access internet.

Server: Pi3
Created an user profile using 'pivpn add'

Client: Ubuntu 18.04 

'$ sudo openvpn ubuntu-client.ovpn 
Wed Mar 20 15:32:59 2019 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2018
Wed Mar 20 15:32:59 2019 library versions: OpenSSL 1.1.0g  2 Nov 2017, LZO 2.08
Wed Mar 20 15:32:59 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Enter Private Key Password: ********
Wed Mar 20 15:33:04 2019 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Wed Mar 20 15:33:04 2019 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Mar 20 15:33:04 2019 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Wed Mar 20 15:33:04 2019 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Mar 20 15:33:04 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]<IP:Port>
Wed Mar 20 15:33:04 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Wed Mar 20 15:33:04 2019 UDP link local: (not bound)
Wed Mar 20 15:33:04 2019 UDP link remote: [AF_INET]<IP:Port>
Wed Mar 20 15:33:04 2019 TLS: Initial packet from [AF_INET]<IP:Port>, sid=75b3b45f 8af694ec
Wed Mar 20 15:33:04 2019 VERIFY OK: depth=1, CN=ChangeMe
Wed Mar 20 15:33:04 2019 VERIFY KU OK
Wed Mar 20 15:33:04 2019 Validating certificate extended key usage
Wed Mar 20 15:33:04 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed Mar 20 15:33:04 2019 VERIFY EKU OK
Wed Mar 20 15:33:04 2019 VERIFY X509NAME OK: CN=serve_<name>
Wed Mar 20 15:33:04 2019 VERIFY OK: depth=0, CN=serve_<name>
Wed Mar 20 15:33:04 2019 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-ECDSA-AES256-GCM-SHA384, 256 bit EC, curve: prime256v1
Wed Mar 20 15:33:04 2019 [serve_<name>] Peer Connection Initiated with [AF_INET]<IP:Port>
Wed Mar 20 15:33:05 2019 SENT CONTROL [serve_<name>]: 'PUSH_REQUEST' (status=1)
Wed Mar 20 15:33:05 2019 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 8.8.8.8,dhcp-option DNS 8.8.4.4,redirect-gateway def1,route-gateway 10.8.0.1,topology subnet,ping 1800,ping-restart 3600,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,cipher AES-256-GCM'
Wed Mar 20 15:33:05 2019 OPTIONS IMPORT: timers and/or timeouts modified
Wed Mar 20 15:33:05 2019 OPTIONS IMPORT: --ifconfig/up options modified
Wed Mar 20 15:33:05 2019 OPTIONS IMPORT: route options modified
Wed Mar 20 15:33:05 2019 OPTIONS IMPORT: route-related options modified
Wed Mar 20 15:33:05 2019 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Wed Mar 20 15:33:05 2019 OPTIONS IMPORT: peer-id set
Wed Mar 20 15:33:05 2019 OPTIONS IMPORT: adjusting link_mtu to 1624
Wed Mar 20 15:33:05 2019 OPTIONS IMPORT: data channel crypto options modified
Wed Mar 20 15:33:05 2019 Data Channel: using negotiated cipher 'AES-256-GCM'
Wed Mar 20 15:33:05 2019 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Wed Mar 20 15:33:05 2019 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Wed Mar 20 15:33:05 2019 ROUTE_GATEWAY 10.34.160.1/255.255.240.0 IFACE=wlp2s0 HWADDR=<MAC>
Wed Mar 20 15:33:05 2019 TUN/TAP device tun0 opened
Wed Mar 20 15:33:05 2019 TUN/TAP TX queue length set to 100
Wed Mar 20 15:33:05 2019 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Wed Mar 20 15:33:05 2019 /sbin/ip link set dev tun0 up mtu 1500
Wed Mar 20 15:33:05 2019 /sbin/ip addr add dev tun0 10.8.0.2/24 broadcast 10.8.0.255
Wed Mar 20 15:33:05 2019 /etc/openvpn/update-resolv-conf tun0 1500 1552 10.8.0.2 255.255.255.0 init
Wed Mar 20 15:33:05 2019 /sbin/ip route add <IP>/32 via 10.34.160.1
Wed Mar 20 15:33:05 2019 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1
Wed Mar 20 15:33:05 2019 /sbin/ip route add 128.0.0.0/1 via 10.8.0.1
Wed Mar 20 15:33:05 2019 Initialization Sequence Completed'

On server side: '/var/log/openvpn.log' shows

'Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 TLS: Initial packet from [AF_INET]10.34.160.90:43825, sid=87ae9bd1 41c062c7
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 VERIFY OK: depth=1, CN=ChangeMe
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 Validating certificate key usage
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 ++ Certificate has key usage  0080, expects 0080
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 VERIFY KU OK
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 Validating certificate extended key usage
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 ++ Certificate has EKU (str) TLS Web Client Authentication, expects TLS Web Client Authentication
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 VERIFY EKU OK
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 VERIFY OK: depth=0, CN=ubuntu-client
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 peer info: IV_VER=2.4.4
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 peer info: IV_PLAT=linux
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 peer info: IV_PROTO=2
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 peer info: IV_NCP=2
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 peer info: IV_LZ4=1
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 peer info: IV_LZ4v2=1
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 peer info: IV_LZO=1
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 peer info: IV_COMP_STUB=1
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 peer info: IV_COMP_STUBv2=1
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 peer info: IV_TCPNL=1
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-ECDSA-AES256-GCM-SHA384
Mar 20 15:33:04 pi ovpn-server[464]: 10.34.160.90:43825 [ubuntu-client] Peer Connection Initiated with [AF_INET]10.34.160.90:43825
Mar 20 15:33:04 pi ovpn-server[464]: MULTI: new connection by client 'ubuntu-client' will cause previous active sessions by this client to be dropped.  Remember to use the --duplicate-cn option if you want multiple clients using the same certificate or username to concurrently connect.
Mar 20 15:33:04 pi ovpn-server[464]: MULTI_sva: pool returned IPv4=10.8.0.2, IPv6=(Not enabled)
Mar 20 15:33:04 pi ovpn-server[464]: MULTI: Learn: 10.8.0.2 -> ubuntu-client/10.34.160.90:43825
Mar 20 15:33:04 pi ovpn-server[464]: MULTI: primary virtual IP for ubuntu-client/10.34.160.90:43825: 10.8.0.2
Mar 20 15:33:05 pi ovpn-server[464]: ubuntu-client/10.34.160.90:43825 PUSH: Received control message: 'PUSH_REQUEST'
Mar 20 15:33:05 pi ovpn-server[464]: ubuntu-client/10.34.160.90:43825 SENT CONTROL [ubuntu-client]: 'PUSH_REPLY,dhcp-option DNS 8.8.8.8,dhcp-option DNS 8.8.4.4,redirect-gateway def1,route-gateway 10.8.0.1,topology subnet,ping 1800,ping-restart 3600,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,cipher AES-256-GCM' (status=1)
Mar 20 15:33:05 pi ovpn-server[464]: ubuntu-client/10.34.160.90:43825 Data Channel Encrypt: Cipher 'AES-256-GCM' initialized with 256 bit key
Mar 20 15:33:05 pi ovpn-server[464]: ubuntu-client/10.34.160.90:43825 Data Channel Decrypt: Cipher 'AES-256-GCM' initialized with 256 bit key'

PS: I am able to run connect and access internet from android OpenVPN connect client App.

**Comment by orazioedoardo** [comment]
Where are you connecting your ubuntu client from? 10.34.160.90 looks like a private IP. Is it an IP from the same subnet as your raspberry pi network? What if you try to connect from a cellular network?

Post the output of `sudo iptables -S` and `sudo iptables -t nat -S` from your raspberry pi so we can check the firewall rules.

**Comment by vik0** [comment]
Ubuntu client is in a different subnet than raspberry pi. Pi's subnet is `192.168.1.*`. I am able to connect from the cellular network but still unable to access the local network. Is it not possible to access the server if I ubuntu client has a different subnet?

`sudo iptables -S`
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N ufw-after-forward
-N ufw-after-input
-N ufw-after-logging-forward
-N ufw-after-logging-input
-N ufw-after-logging-output
-N ufw-after-output
-N ufw-before-forward
-N ufw-before-input
-N ufw-before-logging-forward
-N ufw-before-logging-input
-N ufw-before-logging-output
-N ufw-before-output
-N ufw-reject-forward
-N ufw-reject-input
-N ufw-reject-output
-N ufw-track-forward
-N ufw-track-input
-N ufw-track-output
-A INPUT -j ufw-before-logging-input
-A INPUT -j ufw-before-input
-A INPUT -j ufw-after-input
-A INPUT -j ufw-after-logging-input
-A INPUT -j ufw-reject-input
-A INPUT -j ufw-track-input
-A FORWARD -j ufw-before-logging-forward
-A FORWARD -j ufw-before-forward
-A FORWARD -j ufw-after-forward
-A FORWARD -j ufw-after-logging-forward
-A FORWARD -j ufw-reject-forward
-A FORWARD -j ufw-track-forward
-A OUTPUT -j ufw-before-logging-output
-A OUTPUT -j ufw-before-output
-A OUTPUT -j ufw-after-output
-A OUTPUT -j ufw-after-logging-output
-A OUTPUT -j ufw-reject-output
-A OUTPUT -j ufw-track-output
```

I am not sure why it has so many entries. (I am running a pihole server aswell).

`sudo iptables -t nat -S`

```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o interface -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
```

Yes, I have enabled IP forwarding. 
```
$cat /proc/sys/net/ipv4/ip_forward
1
```

It's weird that I am able to ping google but unable to open it on the browser.

Thanks!

**Comment by orazioedoardo** [comment]
> Is it not possible to access the server if ubuntu client has a different subnet?

Actually you do have to use different subnets. However your raspberry pi reported that your ubuntu client connected to it using 10.34.160.90. Usually what you see is the PUBLIC ip of the client. So i assume you are not connecting remotely. What's your network topology? By the way the openvpn.log does not report an error so the problem could only be this bogus rule `-A POSTROUTING -s 10.8.0.0/24 -o interface -j MASQUERADE`.

Try this:
`sudo iptables -t nat -F`
`sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE`

**Comment by orazioedoardo** [comment]
Post the output of `sudo cat /etc/openvpn/easy-rsa/pki/Default.txt` as well. The remote line contains the public ip or domain you chose during the installation so you may want to omit that.

**Comment by vik0** [comment]
My raspberry pi is behind a router (both my router and Pi have static IP addresses, router has a public IP as well) which is located in my institute. Ubuntu client is behind another router from the same institute.

I tried 
`sudo iptables -t nat -F`
`sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE`

I am still able to ping google, other websites but unable to open any website. 

output of `tail -10 /var/log/penvpn.log`
```
Mar 21 05:56:49 pi ovpn-server[362]: ubuntu-client/10.30.18.67:49723 IP packet with unknown IP version=15 seen
Mar 21 05:56:49 pi ovpn-server[362]: ubuntu-client/10.30.18.67:49723 IP packet with unknown IP version=15 seen
Mar 21 05:56:49 pi ovpn-server[362]: ubuntu-client/10.30.18.67:49723 IP packet with unknown IP version=15 seen
Mar 21 05:56:50 pi ovpn-server[362]: ubuntu-client/10.30.18.67:49723 IP packet with unknown IP version=15 seen
Mar 21 05:56:50 pi ovpn-server[362]: ubuntu-client/10.30.18.67:49723 IP packet with unknown IP version=15 seen
Mar 21 05:56:50 pi ovpn-server[362]: ubuntu-client/10.30.18.67:49723 IP packet with unknown IP version=15 seen
Mar 21 05:56:50 pi ovpn-server[362]: ubuntu-client/10.30.18.67:49723 IP packet with unknown IP version=15 seen
Mar 21 05:56:50 pi ovpn-server[362]: ubuntu-client/10.30.18.67:49723 IP packet with unknown IP version=15 seen
Mar 21 05:56:50 pi ovpn-server[362]: ubuntu-client/10.30.18.67:49723 IP packet with unknown IP version=15 seen
Mar 21 05:56:51 pi ovpn-server[362]: ubuntu-client/10.30.18.67:49723 IP packet with unknown IP version=15 seen
```

**Comment by orazioedoardo** [comment]
Are you getting `IP packet with unknown IP version=15 seen` if you connect from a cellular network?

**Comment by vik0** [comment]
Yes. 
```
$ sudo tail -10 /var/log/openvpn.log 
Mar 22 00:11:50 pi ovpn-server[559]: ubuntu-client/172.56.38.100:47199 IP packet with unknown IP version=15 seen
Mar 22 00:11:50 pi ovpn-server[559]: ubuntu-client/172.56.38.100:47199 IP packet with unknown IP version=15 seen
Mar 22 00:11:50 pi ovpn-server[559]: ubuntu-client/172.56.38.100:47199 IP packet with unknown IP version=15 seen
Mar 22 00:11:50 pi ovpn-server[559]: ubuntu-client/172.56.38.100:47199 IP packet with unknown IP version=15 seen
Mar 22 00:11:50 pi ovpn-server[559]: ubuntu-client/172.56.38.100:47199 IP packet with unknown IP version=15 seen
Mar 22 00:11:50 pi ovpn-server[559]: ubuntu-client/172.56.38.100:47199 IP packet with unknown IP version=15 seen
Mar 22 00:11:50 pi ovpn-server[559]: ubuntu-client/172.56.38.100:47199 IP packet with unknown IP version=15 seen
Mar 22 00:11:50 pi ovpn-server[559]: ubuntu-client/172.56.38.100:47199 IP packet with unknown IP version=15 seen
Mar 22 00:11:51 pi ovpn-server[559]: ubuntu-client/172.56.38.100:47199 IP packet with unknown IP version=15 seen
Mar 22 00:11:54 pi ovpn-server[559]: ubuntu-client/172.56.38.100:47199 IP packet with unknown IP version=15 seen`
```

I am bit confused because I am able to access internet on both windows and android but not on Ubuntu. Are there any ubuntu specific settings which needs to be enabled/modified. 

Thanks for looking into this.

**Comment by devZer0** [comment]
why should pivpn support ubuntu 18.04 lts when their network manager does not even support tls-crypt, and so you won't even be able to connect to pivpn with ubuntu 18.04 openvpn client ?

https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1749562?comments=all

**Comment by orazioedoardo** [comment]
@devZer0 pivpn supports ubuntu 18.04 as a server, not as a client (which still works if you connect from the command line).

@vik0 sorry for not answering, I didn’t know how to help at that point and then i forgot about it. Perhaps you should check whether you have openvpn 2.4 or later on ubuntu.

**Comment by vik0** [comment]
Hi @orazioedoardo no problem! Yes, both client and server have OpenVPN 2.4.0 or later.

Don't worry, I have decided to use it on Windows! Thanks a lot for helping until now. PiVPN is awesome!

**Comment by 4s3ti** [comment]
this has been merged today into Master branch. 
Closing
